spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    jdbc-url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframwork:
        security:
          OFF
app:
  security:
    jwt:
      secret-key: 3F4528482B4D6251655468576D5A7134743777217A24432646294A404E635266
      expiration: 604800000 # a day  86400000
      refresh-token:
        expiration: 604800000 # 7 days


