spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wmm
    jdbc-url: jdbc:mysql://localhost:3306/wmm
    username: root
    password: achraf
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframwork:
        security:
          OFF
app:
  security:
    jwt:
      secret-key: 3F4528482B4D6251655468576D5A7134743777217A24432646294A404E635266
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


